# Generated by Django 3.1.7 on 2021-04-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassNotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngClassNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chapter', models.CharField(max_length=300)),
                ('EngNotesFile', models.FileField(upload_to='Eng_Notes')),
            ],
        ),
        migrations.DeleteModel(
            name='EngNotes',
        ),
    ]
