# Generated by Django 3.1.7 on 2021-04-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassNotes', '0002_auto_20210410_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='HinClassNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chapter', models.CharField(max_length=300)),
                ('HinNotesFile', models.FileField(upload_to='Hin_Notes')),
            ],
        ),
    ]
