# Generated by Django 3.1.7 on 2021-04-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassNotes', '0003_hinclassnotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AraClassNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chapter', models.CharField(max_length=300)),
                ('AraNotesFile', models.FileField(upload_to='Arabic_Notes')),
            ],
        ),
    ]
