# Generated by Django 3.1.7 on 2021-04-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassNotes', '0005_matclassnotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssClassNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chapter', models.CharField(max_length=300)),
                ('IssNotesFile', models.FileField(upload_to='Indian_SST_Notes')),
            ],
        ),
        migrations.CreateModel(
            name='SciClassNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chapter', models.CharField(max_length=300)),
                ('SciNotesFile', models.FileField(upload_to='Science_Notes')),
            ],
        ),
        migrations.CreateModel(
            name='UssClassNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chapter', models.CharField(max_length=300)),
                ('UssNotesFile', models.FileField(upload_to='UAE_SST_Notes')),
            ],
        ),
    ]
