# Generated by Django 3.1.7 on 2021-04-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AraWS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chapter', models.CharField(max_length=300)),
                ('AraWSFile', models.FileField(upload_to='ArabicWS')),
            ],
        ),
        migrations.CreateModel(
            name='HinWS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chapter', models.CharField(max_length=300)),
                ('HinWSFile', models.FileField(upload_to='HindiWS')),
            ],
        ),
        migrations.CreateModel(
            name='IssWS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chapter', models.CharField(max_length=300)),
                ('IssWSFile', models.FileField(upload_to='IndianSSTWS')),
            ],
        ),
        migrations.CreateModel(
            name='MatWS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chapter', models.CharField(max_length=300)),
                ('MatWSFile', models.FileField(upload_to='MathsWS')),
            ],
        ),
        migrations.CreateModel(
            name='SciWS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chapter', models.CharField(max_length=300)),
                ('SciWSFile', models.FileField(upload_to='ScienceWS')),
            ],
        ),
        migrations.CreateModel(
            name='UssWS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chapter', models.CharField(max_length=300)),
                ('UssWSFile', models.FileField(upload_to='UAESSTWS')),
            ],
        ),
    ]
